name: mouttet salon
favicon: null
layout_spectrum: 0.50011
typography_spectrum: 0.20705790491774678
title: Organic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c0c0c0'
    - '#e18a07'
    - '#606060'
  brandStrength: 0.21803313144482672
  lightness: 0.5625
  saturation: 0.9214686523191631
  rhythmicContrast: 0.030116100795567036
purpose: []
